Repository Q-CARD/QCard-client, pull requests merged in 2023-09, with the labels that each got.

#39 fix: 메인페이지 하단 카테고리 카드 category key -> name 수정
  src/app/page.tsx
Labels: bug

#40 bufFix: getAccountsProfile 응답값 필드 맞추어 수정
  src/app/auth/login/page.tsx
Labels: bug

#58 feat: API 응답 구조 변경 반영-2
  src/app/category/question/[id]/page.tsx
  src/app/category/result/[id]/page.tsx
  src/app/interview/finish/page.tsx
  src/app/mypage/answer/page.tsx
  src/app/page.tsx
  src/components/Button.tsx
  src/components/Input.tsx
  src/components/Profile.tsx
  src/components/Recoder.jsx
  src/components/TextBoxWrapper.tsx
  src/components/Textarea.tsx
  src/components/ValidationMessage.tsx
  src/store/recoil.ts
  src/styles/styles.ts
  src/types/index.ts
  src/utils/routeByUserAnswered.tsx
  yarn.lock
Labels: enhancement

#59 [배포] develop -> main
  .pnp.cjs
  package.json
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/category/question/[id]/page.tsx
  src/app/category/result/[id]/page.tsx
  src/app/interview/finish/page.tsx
  src/app/interview/followup/page.tsx
  src/app/interview/page.tsx
  src/app/interview/question/layout.tsx
  src/app/interview/question/page.tsx
  src/app/interview/result/[interviewid]/page.tsx
  src/app/interview/result/layout.tsx
  src/app/interview/result/loading.tsx
  src/app/interview/result/page.tsx
  src/app/mypage/answer/page.tsx
  src/app/page.tsx
  src/assets/images/Question Card.png
  src/components/Button.tsx
  src/components/Input.tsx
  src/components/Markdown.tsx
  src/components/Pagination.tsx
  src/components/Profile.tsx
  src/components/Recoder.jsx
  src/components/TextBoxWrapper.tsx
  src/components/Textarea.tsx
  src/components/ValidationMessage.tsx
  src/components/card/DailyQuestionCard.tsx
  src/components/card/QuestionCard.tsx
  src/components/card/QuestionDetailCard.tsx
  src/components/interview/FollowupButton.tsx
  src/components/interview/NextButton.tsx
  src/components/interview/Question.tsx
  src/components/interview/index.tsx
  src/constants/constants.tsx
  src/constants/data.tsx
  src/constants/regex.ts
  src/store/recoil.ts
  src/types/answer.ts
  src/types/index.ts
  src/utils/axios.ts
  src/utils/parseData.ts
  src/utils/routeByUserAnswered.tsx
  yarn.lock
Labels: release

#61 fix: 모의면접 녹음 최소 시간 변경
  .gitignore
  package.json
  src/api/interview.ts
  src/app/interview/followup/page.tsx
  src/app/interview/page.tsx
  src/app/interview/question/page.tsx
  src/app/page.tsx
  src/components/Accordian.tsx
  src/components/Checkbox.tsx
  src/components/Pagination.tsx
  src/components/Recoder.jsx
  src/components/Timer.tsx
  src/components/card/RecordCard.tsx
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatRoom.tsx
  src/components/interview/FollowupButton.tsx
  src/components/interview/NextButton.tsx
  src/components/interview/Question.tsx
  src/constants/constants.tsx
  src/store/recoil.ts
  src/types/index.ts
  src/utils/atom.ts
  src/utils/utils.ts
  yarn.lock
Labels: enhancement

#73 refactor: 녹음 기능 useReducer 마이그레이션
  src/app/interview/question/page.tsx
  src/assets/icons/icon-circle-blue.png
  src/assets/icons/icon-circle-grey.png
  src/assets/icons/icon-mic-blue.png
  src/assets/icons/icon-mic-grey.png
  src/assets/icons/icon-record-pause.png
  src/components/Recoder.jsx
  src/components/Timer.tsx
  src/components/card/RecordCard.tsx
  src/constants/constants.tsx
  src/types/index.ts
Labels: refactor

#78 feat: 메인 페이지 UI 디벨롭
  .pnp.cjs
  src/app/interview/page.tsx
  src/app/page.tsx
  src/assets/images/image-interview-illust.png
  src/assets/images/image-main-category.png
  src/components/card/DailyQuestionCard.tsx
  src/components/common/Button.tsx
  src/components/common/index.tsx
  src/components/main/MockInterview.tsx
  tailwind.config.ts
  yarn.lock
Labels: enhancement

#79 feat: 모의면접 결과 & 꼬리질문 UI 디벨롭
  .gitignore
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/category/question/[id]/page.tsx
  src/app/interview/followup/layout.tsx
  src/app/interview/followup/page.tsx
  src/app/interview/question/page.tsx
  src/app/interview/result/layout.tsx
  src/app/interview/result/page.tsx
  src/app/mypage/answer/page.tsx
  src/app/page.tsx
  src/components/chat/ChatBubble.tsx
  src/components/chat/ChatInput.tsx
  src/components/chat/ChatRoom.tsx
  src/components/common/Footer.tsx
  src/components/common/Textarea.tsx
  src/components/common/index.tsx
  src/components/interview/Accordian.tsx
  src/components/interview/FollowupButton.tsx
  src/components/interview/FollowupCard.tsx
  src/components/interview/InterviewQuestionSection.tsx
  src/components/interview/RecordCard.tsx
  src/components/interview/Timer.tsx
  src/components/interview/index.tsx
  src/constants/common.tsx
  src/types/index.ts
  src/utils/fetch.ts
Labels: enhancement
